TrainingApplication/Controllers/NewUserRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingApplication.DAL;
using TrainingApplication.Models;

namespace TrainingApplication.Controllers
{
    public class NewUserRegistrationController : Controller
    {
        private Programinfo db = new Programinfo();

        // GET: NewUserRegistration
        public ActionResult Index()
        {
           
            return View(db.newUserRegistrations.ToList());
        }

        // GET: NewUserRegistration/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewUserRegistration newUserRegistration = db.newUserRegistrations.Find(id);
            if (newUserRegistration == null)
            {
                return HttpNotFound();
            }
            return View(newUserRegistration);
        }

        // GET: NewUserRegistration/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewUserRegistration/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,Username,Password,ConfirmPassword,Email,CreatedDate,LastLoginDate")] NewUserRegistration newUserRegistration)
        {
            if (ModelState.IsValid)
            {
                db.newUserRegistrations.Add(newUserRegistration);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(newUserRegistration);
        }

        // GET: NewUserRegistration/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewUserRegistration newUserRegistration = db.newUserRegistrations.Find(id);
            if (newUserRegistration == null)
            {
                return HttpNotFound();
            }
            return View(newUserRegistration);
        }

        // POST: NewUserRegistration/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,Username,Password,ConfirmPassword,Email,CreatedDate,LastLoginDate")] NewUserRegistration newUserRegistration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(newUserRegistration).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newUserRegistration);
        }

        // GET: NewUserRegistration/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewUserRegistration newUserRegistration = db.newUserRegistrations.Find(id);
            if (newUserRegistration == null)
            {
                return HttpNotFound();
            }
            return View(newUserRegistration);
        }

        // POST: NewUserRegistration/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NewUserRegistration newUserRegistration = db.newUserRegistrations.Find(id);
            db.newUserRegistrations.Remove(newUserRegistration);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrainingApplication/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingApplication.DAL;
using TrainingApplication.Models;

namespace TrainingApplication.Controllers
{
    public class RoomController : Controller
    {
        private Programinfo db = new Programinfo();

        // GET: Room
        public ActionResult Index()
        {
            return View(db.Rooms.ToList());
        }

        // GET: Room/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // GET: Room/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Room/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "roomNo,roomName")] Room room)
        {
            if (ModelState.IsValid)
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(room);
        }

        // GET: Room/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: Room/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "roomNo,roomName")] Room room)
        {
            if (ModelState.IsValid)
            {
                db.Entry(room).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit");
            }
            return View(room);
        }

        // GET: Room/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: Room/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Room room = db.Rooms.Find(id);
            db.Rooms.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrainingApplication/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingApplication.DAL;
using TrainingApplication.Models;

namespace TrainingApplication.Controllers
{
    public class UserLoginController : Controller
    {
        private Programinfo db = new Programinfo();

        // GET: UserLogin
        //public ActionResult Index()
        //{
        //    return View(db.UserLogins.ToList());
        //}
        public ActionResult LogIn()
        {
            return View();
        }
        public ActionResult AdminLogin()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdminLogin(UserLogin reg)
        {
            if (ModelState.IsValid)
            {
                var details = (from userlist in db.newUserRegistrations
                               where userlist.Username == reg.Username && userlist.Password == reg.Password
                               select new
                               {
                                   userlist.UserId,
                                   userlist.Username
                               }).ToList();


                if (details.FirstOrDefault() != null)
                {
                    Session["UserId"] = details.FirstOrDefault().UserId;
                    Session["Username"] = details.FirstOrDefault().Username;
                    return RedirectToAction("wellcomeAdmin");
                }
            }
            else
            {
                ModelState.AddModelError("", "Invalid credentials");
            }
            return View(reg);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(UserLogin reg)
        {
            if (ModelState.IsValid)
            {
                var details = (from userlist in db.newUserRegistrations
                               where userlist.Username == reg.Username && userlist.Password == reg.Password
                               select new
                               {
                                   userlist.UserId,
                                   userlist.Username
                               }).ToList();

                
                if (details.FirstOrDefault() != null)
                {
                    Session["UserId"] = details.FirstOrDefault().UserId;
                    Session["Username"] = details.FirstOrDefault().Username;
                    return RedirectToAction("wellcome");
                }
            }
            else
            {
                ModelState.AddModelError("", "Invalid credentials");
            }
            return View(reg);
        }
        public ActionResult wellcome()
        {
            return View();

        }
        public ActionResult wellcomeAdmin()
        {
            return View();

        }
        // GET: UserLogin/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    UserLogin userLogin = db.UserLogins.Find(id);
        //    if (userLogin == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(userLogin);
        //}

        //// GET: UserLogin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserLogin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,Username,Password")] UserLogin userLogin)
        {
            if (ModelState.IsValid)
            {
                db.UserLogins.Add(userLogin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userLogin);
        }

        //// GET: UserLogin/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    UserLogin userLogin = db.UserLogins.Find(id);
        //    if (userLogin == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(userLogin);
        //}

        //// POST: UserLogin/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "UserId,Username,Password")] UserLogin userLogin)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(userLogin).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(userLogin);
        //}

        //// GET: UserLogin/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    UserLogin userLogin = db.UserLogins.Find(id);
        //    if (userLogin == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(userLogin);
        //}

        //// POST: UserLogin/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    UserLogin userLogin = db.UserLogins.Find(id);
        //    db.UserLogins.Remove(userLogin);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrainingApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Training Program Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*@Session["Username"].ToString()*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Training Program Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    
                    <li>@Html.ActionLink("New user Registration", "Create", "NewUserRegistration")</li>
                    <li class=" dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            User
                            <span class=" caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Login", "LogIn", "UserLogin")</li>
                            <li>@Html.ActionLink("Logout", "Index", "Home")</li>
                            
                        </ul>
                    </li>
                    <li class=" dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Admin
                            <span class=" caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Login", "AdminLogin", "UserLogin")</li>
                            <li>@Html.ActionLink("Logout", "Index", "Home")</li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Training Program Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TrainingApplication/Views/Shared/_aLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Training Program Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*@Session["Username"].ToString()*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Training Program Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                   
                   
                    <li class=" dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Admin
                            <span class=" caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                           
                            <li>@Html.ActionLink("Logout", "Index", "Home")</li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Training Program Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TrainingApplication/Views/Shared/_myLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Training Program Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Training Program Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                   

                    <li class=" dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Training
                                <span class=" caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("List Of Programs", "Index", "CreateNewTrainingProgram")</li>
                                <li>@Html.ActionLink("Create New Training  Program ", "Create", "CreateNewTrainingProgram")</li>
                                <li>@Html.ActionLink("Manage Programs", "Index", "Room")</li>
                            </ul>
                        </li>
                        <li class=" dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Meeting
                                <span class=" caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Meeting List", "Index", "CreateNewMeetingProgram")</li>
                                <li>@Html.ActionLink("Create New Meeting Programs", "Create", "CreateNewMeetingProgram")</li>
                                <li>@Html.ActionLink("Schedule", "Details", "CreateNewMeetingProgram")</li>
                            </ul>
                        </li>
                    @*<li>@Html.ActionLink("New user Registration", "Create", "NewUserRegistration")</li>*@
                    <li class=" dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            User
                            <span class=" caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            @*<li>@Html.ActionLink("Login", "LogIn", "NewUserRegistration")</li>*@
                            <li>@Html.ActionLink("Logout", "Index", "Home")</li>

                        </ul>
                    </li>
                    <li class=" dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Admin
                            <span class=" caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Login", "AdminLogin", "UserLogin")</li>
                            <li>@Html.ActionLink("Logout", "Index", "Home")</li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Training Program Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>